version: "3.9"
services:
  node-red:
    build: node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    environment:
      # DB_USER: root
      # DB_PASS: pass
      # DB_HOST: db
      # DB_PORT: 3306
      # DB_DATABASE: demo
      OUT_PATH: output
      IN_PATH: input
      JOBINDSATS_API_KEY: ${JOBINDSATS_API_KEY}
            
      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.
    volumes:
      - "./node-red/:/data" 
      
networks: 
  node_red:
    name: node_red
