version: "3.9"
services:
  node-red:
    build: node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    environment:
      REMOTE_IN_PATH: demo
      REMOTE_IN_FAILED_PATH: demo
      REMOTE_IN_IMPORTED_PATH: demo
      REMOTE_OUT_PATH: demo
      FTP_USER: demo
      FTP_PASS: pass
      FTP_PORT: 22
      FTP_HOST: ftp
            
      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.
    volumes:
      - "./node-red/:/data"

    depends_on: 
      - ftp

  ftp:
    image: atmoz/sftp:latest
    restart: always
    command: demo:pass:::demo
    ports:
      - "22:22"
    networks:
      - node_red
      
networks: 
  node_red:
    name: node_red